**Web Scraping with pandas.**

Disclaimer: This only works if the website has tables.

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
import pandas as pd

In [3]:
url = 'https://en.wikipedia.org/wiki/List_of_countries_in_the_Eurovision_Song_Contest'

country = pd.read_html(url)
df = country[1]
df.head(30)

,Country,Broadcaster(s)[12],Debut year,Most recent entry,Entries,Finals,Times qualified,Qualification rate,Most recent final,Wins,Most recent win
0,Albania,RTSH,2004,2023,19,11,10/18,56%,2023.0,0,NaN
1,Andorra †,RTVA,2004,2009,6,0,0/6,0%,NaN,0,NaN
2,Armenia,AMPTV,2006,2023,15,12,11/14,79%,2023.0,0,NaN
3,Australia,SBS,2015,2023,8,7,6/7,86%,2023.0,0,NaN
4,Austria,ORF,1957,2023,55,48,6/13,46%,2023.0,2,2014.0
5,Azerbaijan,İTV,2008,2023,15,13,12/14,86%,2022.0,1,2011.0
6,Belarus ◇,BTRC,2004,2019,16,6,6/16,38%,2019.0,0,NaN
7,Belgium,RTBF / VRT[a],1956,2023,64,54,8/18,44%,2023.0,1,1986.0
8,Bosnia and Herzegovina †,BHRT,1993,2016,19,18,7/8,88%,2012.0,0,NaN
9,Bulgaria †,BNT,2005,2022,14,5,5/14,36%,2021.0,0,NaN
10,Croatia,HRT,1993,2023,28,19,7/16,44%,2023.0,0,NaN
11,Cyprus,CyBC,1981,2023,39,32,10/17,59%,2023.0,0,NaN
12,Czechia[b],ČT,2007,2023,11,5,5/11,45%,2023.0,0,NaN
13,Denmark,DR,1957,2023,51,44,10/17,59%,2019.0,3,2013.0
14,Estonia,ERR[c],1994,2023,28,18,9/19,47%,2023.0,1,2001.0
15,Finland,Yle,1961,2023,56,48,9/17,53%,2023.0,1,2006.0
16,France,France Télévisions[d],1956,2023,65,65,Automatic qualifier[e],Automatic qualifier[e],2023.0,5,1977.0
17,Georgia,GPB,2007,2023,15,7,7/15,47%,2016.0,0,NaN
18,Germany,ARD (NDR)[f],1956,2023,66,66,Automatic qualifier[e],Automatic qualifier[e],2023.0,2,2010.0
19,Greece,ERT[g],1974,2023,43,40,13/16,81%,2022.0,1,2005.0
20,Hungary †,MTVA[h],1994,2019,17,14,10/13,77%,2018.0,0,NaN
21,Iceland,RÚV,1986,2023,35,27,10/18,56%,2022.0,0,NaN
22,Ireland,RTÉ,1965,2023,56,45,6/17,35%,2018.0,7,1996.0
23,Israel,IPBC[i],1973,2023,45,38,10/17,59%,2023.0,4,2018.0
24,Italy,RAI,1956,2023,48,48,Automatic qualifier[e],Automatic qualifier[e],2023.0,3,2021.0
25,Latvia,LTV,2000,2023,23,10,5/18,28%,2016.0,1,2002.0
26,Lithuania,LRT,1994,2023,23,16,11/18,61%,2023.0,0,NaN
27,Luxembourg,RTL,1956,1993,37,37,NaN,NaN,1993.0,5,1983.0
28,Malta,PBS,1971,2023,35,26,8/17,47%,2021.0,0,NaN
29,Moldova,TRM,2005,2023,18,13,12/17,71%,2023.0,0,NaN

# New Section

In [ ]:
url2 = 'https://waploaded.com/'

six = pd.read_html(url2)
df = six[6]
df.head(10)

ValueError: No tables found